### ISSUE TITLE
27.0.2 works

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-nextcloud#31]
using the following stanza in docker-compose.yml proves the most recent version works:
```
  build: 
      context: https://github.com/tiredofit/docker-nextcloud.git#27-3.6.4
      args: 
        NEXTCLOUD_VERSION: 27.0.2
```
